tasks:
- volumes_upgrade.setup:
    io_clients: [client.0, client.1, client.2]
    admin_client: client.3
- print: "**** done creating v2 subvolumes, clients doing IO, clones and purges paused mid-way"
