tasks:
- exec:
    mon.a:
      - ceph auth wipe-rotating-service-keys
      - ceph auth --format=json-pretty dump-keys
      - ceph auth --format=json dump-keys | jq '.data.rotating_secrets | all(  if .key == 32 then  (.val.secrets | all(.val.key.type == 1))  else  (.val.secrets | all(.val.key.type == 2))  end  )'
      - ceph --log-to-stderr=true --log_to_file=true --debug_ms=5 --debug_auth=30 --debug_monc=30 health unmute AUTH_INSECURE_SERVICE_KEYS_ALLOWED
- ceph.healthy:
