from logging import getLogger
from os.path import join, dirname
from time import sleep

from teuthology.misc import get_testdir


log = getLogger(__name__)


class WriterThreadConf:
    '''
    Configuration options for writer threads that are generated by
    IOWorkloadManager instances.
    '''

    def __init__(self, depth=0, br_factor=0, wr_th_lim=10, wr_th_file_size=1024,
                 wr_th_file_lim=1000, wr_th_str='', wr_th_sleep=0, dir_pfx='dir-',
                 file_pfx='file-'):
        # number of writer threads that run simultaneously
        self.wr_th_lim = wr_th_lim
        # string that will be used by writer thread to write every file
        self.wr_th_str = wr_th_str
        # size of files that writer threads in one go
        self.wr_th_file_size = wr_th_file_size
        # num of files to written by each writer thread
        self.wr_th_file_lim = wr_th_file_lim

        # amount of time writer thread sleep. helps change workload without
        # changing other parameters
        self.wr_th_sleep = wr_th_sleep

        self.dir_pfx = dir_pfx
        self.file_pfx = file_pfx

        # depth for dir hierarchy
        self.depth = depth
        # branching factor for dir hierarchy
        self.br_factor = br_factor

    def get_as_dict(self):
        dict_ = {}
        for attr, value in vars(self).items():
            dict_[attr.upper()] = str(value)
        return dict_


class IoWorkloadManager:
    '''
    Helper class for generating, killing, stopping and resuming IO workload and
    for checking its status.
    '''

    def __init__(self, mounts, wr_th_conf=None, wait=False, timeout=20*60,
                 env={}):
        # gen IO workload through every given mount
        self.mounts = {}
        for mount in mounts:
            self.mounts[mount] = None
        self.wr_th_conf = wr_th_conf if wr_th_conf else WriterThreadConf()

        # run IO worload in background?
        self.wait = wait
        # timeout for IO workload script
        self.timeout = timeout
        # env vars for IO workload script
        self.env = env

        self.script_name = 'gen-io-workload.sh'
        self.remote_test_dir_path = get_testdir()
        self.script_path = join(self.remote_test_dir_path, self.script_name)
        # script path on teuthology worker node
        self.TWN_SCRIPT_PATH = join(dirname(__file__), self.script_name)

        self._write_script_to_remote()
        self.clean_mounts()

    def teardown(self):
        self.kill_all_io_procs()

        for mount_x in self.mounts:
            mount_x.client_remote.run(args=f'rm -f {self.script_path}')

        self.clean_mounts()

    def _write_script_to_remote(self):
        for mount_x in self.mounts:
            # in case different mounts are located on same remote machine,
            # don't waste time copying files again.
            proc = mount_x.client_remote.run(args=f'ls {self.script_path}',
                                             check_status=False)
            if proc.exitstatus == 0:
                continue

            log.info(f'copying file from {self.TWN_SCRIPT_PATH} at teuth worker'
                     f'node to {self.remote_test_dir_path} at this remote node')
            mount_x.client_remote.get_file(self.TWN_SCRIPT_PATH,
                                           dest_dir=self.remote_test_dir_path)
            mount_x.client_remote.run(args=f'sudo chmod 755 {self.script_path}',
                                      omit_sudo=False)

    def wait_for_procs_to_finish(self, procs, sleep_dur=30):
        def proc_finished(proc):
            try:
                proc.wait(timeout=3)
            except TimeoutExpired:
                return False
            else:
                return True

        total_procs = len(procs)
        while procs == []:
            procs = [p for p in procs if not proc_finished(p)]
            log.info(f'waiting for {len(procs)}/{total_procs} deletion threads '
                     'to finish...')
            sleep(sleep_dur)

    def kill_all_io_procs(self):
        assert tuple(self.mounts.values()) != (None, None, None)

        log.info('killing all IO threads...')
        for mount_x, proc in self.mounts.items():
            # pkill sends sigterm here (and by default)
            mount_x.client_remote.run(args=f'pkill -P {proc.subproc.pid}')

        # wait a bit since killing all parent+child processes might take a bit
        # of time
        sleep(5)

        if self.are_all_io_procs_dead():
            log.info('killed all IO threads successfully.')
            self.mounts = {mount_x: '' for mount_x in self.mounts.keys()}
        else:
            log.info('some IO threads are still alive :(')
            raise RuntimeError('all IO threads should\'ve been dead by now')

        self.wait_for_procs_to_finish(tuple(self.mounts.values()), 60)

    def clean_mounts(self):
        '''
        Remove all files from the given mounts. To be run before initiating IO
        workload.
        '''
        del_procs = []
        for mount_x in self.mounts:
            # launch one remove thread per mount and let them run in background
            # simultaneously for faster removing. it's needed since number of
            # files generated can be very huge.
            proc = mount_x.run_shell(args='rm -rf  *', wait=False)
            del_procs.append(proc)

        self.wait_for_procs_to_finish(del_procs)

    def get_alive_io_procs_count(self):
        procs = tuple(self.mounts.values())
        procs_total = len(procs)
        if procs_total == 0:
            return 0
        procs_alive, procs_dead = 0, 0

        for proc in procs:
            if proc.subproc.poll() is None:
                procs_alive += 1
            else:
                procs_dead += 1

        if procs_alive == 0:
            log.info('all IO procs are dead')
        elif procs_dead == 0:
            log.info('all IO procs are alive')
        else:
            log.info(f'IO procs: alive: {procs_alive}, dead: '
                     f'{procs_dead}, total: {procs_total}')

        return procs_alive

    def are_all_io_procs_alive(self):
        return True if self.get_alive_io_procs_count() == len(self.mounts) \
            else False

    def are_all_io_procs_dead(self):
        return True if self.get_alive_io_procs_count() == 0 else False

    def start_io_workload(self):
        assert tuple(self.mounts.values()) == (None, None, None)

        self.env.update(self.wr_th_conf.get_as_dict())

        for i, mount_x in enumerate(self.mounts):
            self.env['DIR_PFX'] = f'dir{i+1}'
            proc = mount_x.run_shell(self.script_path, wait=self.wait,
                                     env=self.env, timeout=self.timeout)
            self.mounts[mount_x] = proc

        sleep(5)
        assert self.are_all_io_procs_alive()

    def pause_io_workload(self):
        assert tuple(self.mounts.values()) != (None, None, None)

        procs = []
        for mount_x, proc_x in self.mounts.items():
            proc = mount_x.run_shell(f'pkill -STOP -P {proc_x.subproc.pid}',
                                     wait=False)
            procs.append(proc)
        self.wait_for_procs_to_finish(procs, 2)

    def resume_io_workload(self):
        assert tuple(self.mounts.values()) != (None, None, None)

        procs = []
        for mount_x, proc_x in self.mounts.items():
            proc = mount_x.run_shell(f'pkill -CONT -P {proc_x.subproc.pid}',
                                     wait=False)
            procs.append(proc)
        self.wait_for_procs_to_finish(procs, 2)
