#!/bin/bash

# clean-ci [--dry-run] [--since="relative date"]
#
# Cleanup the ceph-ci.git repository branch list by deleting any branch with a
# HEAD commit date older than (by default) 3 months.

set -e

CEPH_CI=https://github.com/ceph/ceph-ci.git
DRY_RUN=0
SINCE="3 months ago"


function iterate_ci {
    cutoff_date=$(date -d "$SINCE" +%s)

    git ls-remote --refs --heads "$CEPH_CI" | \
    while read commit_ref; do
        echo "$commit_ref"
        commit=$(cut -f1 <<<"$commit_ref")
        ref=$(cut -f2 <<<"$commit_ref")

        printf 'Examining %s (commit %s)\n' "$ref" "$commit" >&2

        git fetch --quiet --depth=1 "$CEPH_CI" "$commit"

        commit_date=$(git log -1 --format="%ct" "$commit")

        printf '\thas commit date: %s\n' $(date --iso-8601=sec --date="@$commit_date") >&2

        if (( commit_date < three_months_ago )); then
          if [[ DRY_RUN = 0 ]]; then
            echo "Deleting remote ref: $ref"
            git push "$CEPH_CI" --delete "$ref"
          else
            echo "Would delete remote ref: $ref"
          fi
        fi
    done
}

function main {
    eval set -- $(getopt --name "$0" --options 'h' --longoptions 'help,dry-run,since:' -- "$@")

    while [ "$#" -gt 0 ]; do
        case "$1" in
            -h|--help)
                printf '%s: [--dry-run] [--since=<relative time>]\n' "$0"
                exit 0
                ;;
            --dry-run)
                DRY_RUN=1
                shift
                ;;
            --since)
                SINCE="$2"
                shift 2
                ;;
            --)
                shift
                break
                ;;
        esac
    done

    iterate_ci
}

main "$@"
