# N.B. in order to effect a service key wipe, the service daemons must be
# restarted next. During this time, service daemons will be inaccessible to new
# clients.
teuthology:
  variables:
    wipe_service_keys: true
tasks:
- exec:
    mon.a:
      - ceph auth wipe-rotating-service-keys
      - ceph auth --format=json-pretty dump-keys
      - ceph auth --format=json dump-keys | jq '.data.rotating_secrets | all(  if .key == 32 then  (.val.secrets | all(.val.key.type == 1))  else  (.val.secrets | all(.val.key.type == 2))  end  )'
