tasks:
- cephfs_test_runner:
    modules:
      - tasks.cephfs.test_misc.TestMisc.test_write_updates_futuristic_mtime

overrides:
  ceph:
    log-ignorelist:
      - evicting unresponsive client
      - POOL_APP_NOT_ENABLED
      - has not responded to cap revoke by MDS for over
      - MDS_CLIENT_LATE_RELEASE
      - responding to mclientcaps
      - RECENT_CRASH
      - MON_DOWN
