tasks:
- ceph.key_rotate:
    daemons: [mon.*]
    key_type: aes256k
- ceph.key_rotate:
    daemons: [mgr.*, osd.*, mds.*]
    key_type: aes256k
- exec:
    mon.a:
      - ceph --debug_ms=5 --debug_auth=30 --debug_monc=30 auth ls
      - ceph --debug_ms=5 --debug_auth=30 --debug_monc=30 auth --format=json-pretty dump-keys
      - ceph --debug_ms=5 --debug_auth=30 --debug_monc=30 auth --format=json dump-keys | jq 'any(.data.secrets[] | select(.key.type == 1 or .key.type == 2 or .key.type == 4 or .key.type == 16); .val.key.type != 2)'
      - ceph --debug_ms=5 --debug_auth=30 --debug_monc=30 auth --format=json dump-keys | jq '.data.rotating_secrets | all( .val.secrets | all(.val.key.type == 1) )'
      - ceph --debug_ms=5 --debug_auth=30 --debug_monc=30 config set global auth_service_cipher aes256k
