radosbench:
  sequential_yield:
    - radosbench:
        extra_args: --log-to-stderr=false --log_to_file=true --debug_ms=5 --debug_auth=30 --debug_monc=30 --mon_client_target_rank=0
        clients: [client.0]
        time: 300
        unique_pool: true

tasks:
  - sequential_yield:
      - radosbench
