overrides:
  ceph:
    log-ignorelist:
      - Replacing daemon mds
tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_fragment.TestFragmentation.test_finish_old_fragment_auth_pin_race
