tasks:
- ceph:
    cluster-conf:
      global:
        auth service cipher: aes
        cephx preferred cipher: aes
      mon:
        mon auth allow insecure key: true
    cephx:
      key_type: aes
