overrides:
  rgw:
    enable features: [compress-encrypted, transition-reencrypt]
tasks:
- install:
- ceph:
- rgw: [client.0]
- workunit:
    clients:
      client.0:
        - rgw/run-transition-reencrypt.sh
    env:
      TRANSITION_REENCRYPT_PHASE: put
- exec:
    client.0:
      - sudo ceph config set client rgw_crypt_sse_algorithm aes-256-gcm
- ceph.restart:
    daemons: [rgw.*]
- workunit:
    clients:
      client.0:
        - rgw/run-transition-reencrypt.sh
    env:
      TRANSITION_REENCRYPT_PHASE: transition
      TRANSITION_REENCRYPT_EXPECT: SSE-KMS-GCM
