overrides:
  ceph:
    conf:
      client:
        debug client: 20
  check-counter:
    counters:
      mds:
        - "mds.dir_split"
tasks:
- workunit:
    timeout: 5h
    clients:
      all:
        - kernel_untar_build.sh
