name: Check PR dependencies
on: [pull_request_target]
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check PR Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@71c5cc14fab62389a600c0a6e37584dc4916799c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
