name: Check PR dependencies
on: [pull_request_target]
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check PR Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@f4fa19405413bddd2d49fe258f5b571de44cac09
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
