name: Check PR dependencies
on: [pull_request_target]
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check PR Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@e1985f289b7fe06a25327acd061e78bc74865800
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
