---
name: "Pull Request Triage"
on: pull_request_target
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels based on modified files
        # https://github.com/marketplace/actions/labeler?version=v4.0.2
        uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20
        with:
          sync-labels: ''
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Assign to Dashboard project
        # https://github.com/marketplace/actions/add-to-github-projects?version=v0.4.0
        uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        with:
          project-url: https://github.com/orgs/ceph/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: dashboard
      - name: Assign milestone based on target brach name
        # https://github.com/marketplace/actions/pull-request-milestone?version=v1.3.0
        uses: iyu/actions-milestone@e93115c90ff7bcddee71086e9253f1b6a5f4b48a
        with:
          configuration-path: .github/milestone.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
